[project]
name = "df-demo"
version = "0.1.0"
description = "Demo for Data Fabric"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pip>=25.1.1",
    "streamlit>=1.45.1",
]
